const mongoose = require('mongoose');

const xosoResultSchema = new mongoose.Schema({
    date: { type: String, required: true },
    GDBMB: { type: String, required: true },
    G1MB: [String],
    G2MB: [String],
    G3MB: [String],
    G4MB: [String],
    G5MB: [String],
    G6MB: [String],
    G7MB: [String],
    createdAt: { type: Date, default: Date.now },
    MDBMB: [String],

    jackpot: [String],

    LT0MB: [String],
    LT1MB: [String],
    LT2MB: [String],
    LT3MB: [String],
    LT4MB: [String],
    LT5MB: [String],
    LT6MB: [String],
    LT7MB: [String],
    LT8MB: [String],
    LT9MB: [String],

    TKGDB: [String],

    //mn
    GDBHCM: [String],
    G1HCM: [String],
    G2HCM: [String],
    G3HCM: [String],
    G4HCM: [String],
    G5HCM: [String],
    G6HCM: [String],
    G7HCM: [String],
    G8HCM: [String],

    GDBDT: [String],
    G1DT: [String],
    G2DT: [String],
    G3DT: [String],
    G4DT: [String],
    G5DT: [String],
    G6DT: [String],
    G7DT: [String],
    G8DT: [String],

    GDBCM: [String],
    G1CM: [String],
    G2CM: [String],
    G3CM: [String],
    G4CM: [String],
    G5CM: [String],
    G6CM: [String],
    G7CM: [String],
    G8CM: [String],
    GDBDN: [String],
    G1DN: [String],
    G2DN: [String],
    G3DN: [String],
    G4DN: [String],
    G5DN: [String],
    G6DN: [String],
    G7DN: [String],
    G8DN: [String],
    GDBCT: [String],
    G1CT: [String],
    G2CT: [String],
    G3CT: [String],
    G4CT: [String],
    G5CT: [String],
    G6CT: [String],
    G7CT: [String],
    G8CT: [String],
    GDBST: [String],
    G1ST: [String],
    G2ST: [String],
    G3ST: [String],
    G4ST: [String],
    G5ST: [String],
    G6ST: [String],
    G7ST: [String],
    G8ST: [String],
    GDBTN: [String],
    G2TN: [String],
    G3TN: [String],
    G4TN: [String],
    G5TN: [String],
    G6TN: [String],
    G7TN: [String],
    G8TN: [String],

    GDBBTR: [String],
    G1BTR: [String],
    G2BTR: [String],
    G3BTR: [String],
    G4BTR: [String],
    G5BTR: [String],
    G6BTR: [String],
    G7BTR: [String],
    G8BTR: [String],

    GDBVT: [String],
    G1VT: [String],
    G2VT: [String],
    G3VT: [String],
    G4VT: [String],
    G5VT: [String],
    G6VT: [String],
    G7VT: [String],
    G8VT: [String],

    GDBBL: [String],
    G1BL: [String],
    G2BL: [String],
    G3BL: [String],
    G4BL: [String],
    G5BL: [String],
    G6BL: [String],
    G7BL: [String],
    G8BL: [String],

    GDBAG: [String],
    G1AG: [String],
    G2AG: [String],
    G3AG: [String],
    G4AG: [String],
    G5AG: [String],
    G6AG: [String],
    G7AG: [String],
    G8AG: [String],

    GDBBTH: [String],
    G1BTH: [String],
    G2BTH: [String],
    G3BTH: [String],
    G4BTH: [String],
    G5BTH: [String],
    G6BTH: [String],
    G7BTH: [String],
    G8BTH: [String],

    GDBVL: [String],
    G1VL: [String],
    G2VL: [String],
    G3VL: [String],
    G4VL: [String],
    G5VL: [String],
    G6VL: [String],
    G7VL: [String],
    G8VL: [String],

    GDBBD: [String],
    G1BD: [String],
    G2BD: [String],
    G3BD: [String],
    G4BD: [String],
    G5BD: [String],
    G6BD: [String],
    G7BD: [String],
    G8BD: [String],

    GDBTV: [String],
    G1TV: [String],
    G2TV: [String],
    G3TV: [String],
    G4TV: [String],
    G5TV: [String],
    G6TV: [String],
    G7TV: [String],
    G8TV: [String],
    GDBTG: [String],
    G2TG: [String],
    G3TG: [String],
    G4TG: [String],
    G5TG: [String],
    G6TG: [String],
    G7TG: [String],
    G8TG: [String],

    GDBKG: [String],
    G1KG: [String],
    G2KG: [String],
    G3KG: [String],
    G4KG: [String],
    G5KG: [String],
    G6KG: [String],
    G7KG: [String],
    G8KG: [String],

    GDBDL: [String],
    G1DL: [String],
    G2DL: [String],
    G3DL: [String],
    G4DL: [String],
    G5DL: [String],
    G6DL: [String],
    G7DL: [String],
    G8DL: [String],

    LT0DN: [String],
    LT1DN: [String],
    LT2DN: [String],
    LT3DN: [String],
    LT4DN: [String],
    LT5DN: [String],
    LT6DN: [String],
    LT7DN: [String],
    LT8DN: [String],
    LT9DN: [String],
    LT0CT: [String],
    LT1CT: [String],
    LT2CT: [String],
    LT3CT: [String],
    LT4CT: [String],
    LT5CT: [String],
    LT6CT: [String],
    LT7CT: [String],
    LT8CT: [String],
    LT9CT: [String],
    LT0ST: [String],
    LT1ST: [String],
    LT2ST: [String],
    LT3ST: [String],
    LT4ST: [String],
    LT5ST: [String],
    LT6ST: [String],
    LT7ST: [String],
    LT8ST: [String],
    LT9ST: [String],

    LT0BTR: [String],
    LT1BTR: [String],
    LT2BTR: [String],
    LT3BTR: [String],
    LT4BTR: [String],
    LT5BTR: [String],
    LT6BTR: [String],
    LT7BTR: [String],
    LT8BTR: [String],
    LT9BTR: [String],

    LT0VT: [String],
    LT1VT: [String],
    LT2VT: [String],
    LT3VT: [String],
    LT4VT: [String],
    LT5VT: [String],
    LT6VT: [String],
    LT7VT: [String],
    LT8VT: [String],
    LT9VT: [String],

    LT0BL: [String],
    LT1BL: [String],
    LT2BL: [String],
    LT3BL: [String],
    LT4BL: [String],
    LT5BL: [String],
    LT6BL: [String],
    LT7BL: [String],
    LT8BL: [String],
    LT9BL: [String],

    LT0TN: [String],
    LT1TN: [String],
    LT2TN: [String],
    LT3TN: [String],
    LT4TN: [String],
    LT5TN: [String],
    LT6TN: [String],
    LT7TN: [String],
    LT8TN: [String],
    LT9TN: [String],

    LT0AG: [String],
    LT1AG: [String],
    LT2AG: [String],
    LT3AG: [String],
    LT4AG: [String],
    LT5AG: [String],
    LT6AG: [String],
    LT7AG: [String],
    LT8AG: [String],
    LT9AG: [String],

    LT0TG: [String],
    LT1TG: [String],
    LT2TG: [String],
    LT3TG: [String],
    LT4TG: [String],
    LT5TG: [String],
    LT6TG: [String],
    LT7TG: [String],
    LT8TG: [String],
    LT9TG: [String],

    LT0KG: [String],
    LT1KG: [String],
    LT2KG: [String],
    LT3KG: [String],
    LT4KG: [String],
    LT5KG: [String],
    LT6KG: [String],
    LT7KG: [String],
    LT8KG: [String],
    LT9KG: [String],

    LT0DL: [String],
    LT1DL: [String],
    LT2DL: [String],
    LT3DL: [String],
    LT4DL: [String],
    LT5DL: [String],
    LT6DL: [String],
    LT7DL: [String],
    LT8DL: [String],
    LT9DL: [String],

    LT0BTH: [String],
    LT1BTH: [String],
    LT2BTH: [String],
    LT3BTH: [String],
    LT4BTH: [String],
    LT5BTH: [String],
    LT6BTH: [String],
    LT7BTH: [String],
    LT8BTH: [String],
    LT9BTH: [String],

    LT0HCM: [String],
    LT1HCM: [String],
    LT2HCM: [String],
    LT3HCM: [String],
    LT4HCM: [String],
    LT5HCM: [String],
    LT6HCM: [String],
    LT7HCM: [String],
    LT8HCM: [String],
    LT9HCM: [String],

    LT0DT: [String],
    LT1DT: [String],
    LT2DT: [String],
    LT3DT: [String],
    LT4DT: [String],
    LT5DT: [String],
    LT6DT: [String],
    LT7DT: [String],
    LT8DT: [String],
    LT9DT: [String],

    LT0CM: [String],
    LT1CM: [String],
    LT2CM: [String],
    LT3CM: [String],
    LT4CM: [String],
    LT5CM: [String],
    LT6CM: [String],
    LT7CM: [String],
    LT8CM: [String],
    LT9CM: [String],

    LT0BD: [String],
    LT1BD: [String],
    LT2BD: [String],
    LT3BD: [String],
    LT4BD: [String],
    LT5BD: [String],
    LT6BD: [String],
    LT7BD: [String],
    LT8BD: [String],
    LT9BD: [String],

    LT0VL: [String],
    LT1VL: [String],
    LT2VL: [String],
    LT3VL: [String],
    LT4VL: [String],
    LT5VL: [String],
    LT6VL: [String],
    LT7VL: [String],
    LT8VL: [String],
    LT9VL: [String],

    LT0TV: [String],
    LT1TV: [String],
    LT2TV: [String],
    LT3TV: [String],
    LT4TV: [String],
    LT5TV: [String],
    LT6TV: [String],
    LT7TV: [String],
    LT8TV: [String],
    LT9TV: [String],

    //mt
    GDBDLK: [String],
    G1DLK: [String],
    G2DLK: [String],
    G3DLK: [String],
    G4DLK: [String],
    G5DLK: [String],
    G6DLK: [String],
    G7DLK: [String],
    G8DLK: [String],

    GDBQNA: [String],
    G1QNA: [String],
    G2QNA: [String],
    G3QNA: [String],
    G4QNA: [String],
    G5QNA: [String],
    G6QNA: [String],
    G7QNA: [String],
    G8QNA: [String],
    GDBPY: [String],
    G1PY: [String],
    G2PY: [String],
    G3PY: [String],
    G4PY: [String],
    G5PY: [String],
    G6PY: [String],
    G7PY: [String],
    G8PY: [String],

    GDBTTH: [String],
    G1TTH: [String],
    G2TTH: [String],
    G3TTH: [String],
    G4TTH: [String],
    G5TTH: [String],
    G6TTH: [String],
    G7TTH: [String],
    G8TTH: [String],

    GDBKT: [String],
    G1KT: [String],
    G2KT: [String],
    G3KT: [String],
    G4KT: [String],
    G5KT: [String],
    G6KT: [String],
    G7KT: [String],
    G8KT: [String],

    GDBKH: [String],
    G1KH: [String],
    G2KH: [String],
    G3KH: [String],
    G4KH: [String],
    G5KH: [String],
    G6KH: [String],
    G7KH: [String],
    G8KH: [String],

    GDBGL: [String],
    G1GL: [String],
    G2GL: [String],
    G3GL: [String],
    G4GL: [String],
    G5GL: [String],
    G6GL: [String],
    G7GL: [String],
    G8GL: [String],

    GDBNT: [String],
    G1NT: [String],
    G2NT: [String],
    G3NT: [String],
    G4NT: [String],
    G5NT: [String],
    G6NT: [String],
    G7NT: [String],
    G8NT: [String],

    GDBDNA: [String],
    G1DNA: [String],
    G2DNA: [String],
    G3DNA: [String],
    G4DNA: [String],
    G5DNA: [String],
    G6DNA: [String],
    G7DNA: [String],
    G8DNA: [String],

    GDBKH: [String],
    G1KH: [String],
    G2KH: [String],
    G3KH: [String],
    G4KH: [String],
    G5KH: [String],
    G6KH: [String],
    G7KH: [String],
    G8KH: [String],

    GDBQB: [String],
    G1QB: [String],
    G2QB: [String],
    G3QB: [String],
    G4QB: [String],
    G5QB: [String],
    G6QB: [String],
    G7QB: [String],
    G8QB: [String],

    GDBBDI: [String],
    G1BDI: [String],
    G2BDI: [String],
    G3BDI: [String],
    G4BDI: [String],
    G5BDI: [String],
    G6BDI: [String],
    G7BDI: [String],
    G8BDI: [String],

    GDBQT: [String],
    G1QT: [String],
    G2QT: [String],
    G3QT: [String],
    G4QT: [String],
    G5QT: [String],
    G6QT: [String],
    G7QT: [String],
    G8QT: [String],

    LT0DLK: [String],
    LT1DLK: [String],
    LT2DLK: [String],
    LT3DLK: [String],
    LT4DLK: [String],
    LT5DLK: [String],
    LT6DLK: [String],
    LT7DLK: [String],
    LT8DLK: [String],
    LT9DLK: [String],

    LT0QNA: [String],
    LT1QNA: [String],
    LT2QNA: [String],
    LT3QNA: [String],
    LT4QNA: [String],
    LT5QNA: [String],
    LT6QNA: [String],
    LT7QNA: [String],
    LT8QNA: [String],
    LT9QNA: [String],

    LT0GL: [String],
    LT1GL: [String],
    LT2GL: [String],
    LT3GL: [String],
    LT4GL: [String],
    LT5GL: [String],
    LT6GL: [String],
    LT7GL: [String],
    LT8GL: [String],
    LT9GL: [String],

    LT0NT: [String],
    LT1NT: [String],
    LT2NT: [String],
    LT3NT: [String],
    LT4NT: [String],
    LT5NT: [String],
    LT6NT: [String],
    LT7NT: [String],
    LT8NT: [String],
    LT9NT: [String],

    LT0DNA: [String],
    LT1DNA: [String],
    LT2DNA: [String],
    LT3DNA: [String],
    LT4DNA: [String],
    LT5DNA: [String],
    LT6DNA: [String],
    LT7DNA: [String],
    LT8DNA: [String],
    LT9DNA: [String],

    LT0KT: [String],
    LT1KT: [String],
    LT2KT: [String],
    LT3KT: [String],
    LT4KT: [String],
    LT5KT: [String],
    LT6KT: [String],
    LT7KT: [String],
    LT8KT: [String],
    LT9KT: [String],

    LT0TTH: [String],
    LT1TTH: [String],
    LT2TTH: [String],
    LT3TTH: [String],
    LT4TTH: [String],
    LT5TTH: [String],
    LT6TTH: [String],
    LT7TTH: [String],
    LT8TTH: [String],
    LT9TTH: [String],

    LT0KH: [String],
    LT1KH: [String],
    LT2KH: [String],
    LT3KH: [String],
    LT4KH: [String],
    LT5KH: [String],
    LT6KH: [String],
    LT7KH: [String],
    LT8KH: [String],
    LT9KH: [String],

    LT0QB: [String],
    LT1QB: [String],
    LT2QB: [String],
    LT3QB: [String],
    LT4QB: [String],
    LT5QB: [String],
    LT6QB: [String],
    LT7QB: [String],
    LT8QB: [String],
    LT9QB: [String],

    LT0BDI: [String],
    LT1BDI: [String],
    LT2BDI: [String],
    LT3BDI: [String],
    LT4BDI: [String],
    LT5BDI: [String],
    LT6BDI: [String],
    LT7BDI: [String],
    LT8BDI: [String],
    LT9BDI: [String],

    LT0QT: [String],
    LT1QT: [String],
    LT2QT: [String],
    LT3QT: [String],
    LT4QT: [String],
    LT5QT: [String],
    LT6QT: [String],
    LT7QT: [String],
    LT8QT: [String],
    LT9QT: [String],
    //keno
    keno: [String],
    pad_012: [String],
    td_text16: [String],

    //jackpot
    para_open_next: [String],
    number_ball: [String],
    number_ball2: [String],
    text_right: [String],
    para_text_black_bold: [String],
    xsmega: [String],
    jackpot_day: [String],

    //max3d

    max3dg1: [String],
    max3dg24: [String],
    max3dg3: [String],
    titlemax3d: [String],

    //lotogan
    daylotogan: [String],
    lotogan: [String],
    loto: [String],
    daylotogan2: [String],

    //lotogancv
    boso2: [String],
    boso2_ngayve: [String],
    boso2_ngay: [String],

    kep: [String],
    kep_ngayve: [String],
    kep_ngay: [String],
    //tklogandau
    tklogandau: [String],
    tklogandauso: [String],

    tkloganduoiso: [String],

    TKGDBTH: [String],
    phantram_TKLXH: [String],
    luot_TKLXH: [String],
    boso_TKLXH: [String],

    slxh_TKKCB: [String],
    boso_TKKCB: [String],
    top10_TKKCB: [String],

    kyquay_TKKBS: [String],
    lon_TKKBS: [String],
    be_TKKBS: [String],
    chan_TKKBS: [String],
    le_TKKBS: [String],
    combo_TKKBS: [String],

    phantram_TKkdencc: [String],
    luot_TKkdencc: [String],
    boso_TKkdencc: [String],
    haisocuoi: [String],

    G8vGDB_AnGiang: [String],
    G7vG5vG3vG2vG1_AnGiang: [String],
    G6vG4_AnGiang: [String],
    G4_AnGiang: [String],
    LT_AnGiang: [String],

    G8vGDB_DakLak: [String],
    G7vG5vG3vG2vG1_DakLak: [String],
    G6vG4_DakLak: [String],
    G4_DakLak: [String],
    LT_DakLak: [String],

    G8vGDB_DacNong: [String],
    G7vG5vG3vG2vG1_DacNong: [String],
    G6vG4_DacNong: [String],
    G4_DacNong: [String],
    LT_DacNong: [String],

    G8vGDB_GiaLai: [String],
    G7vG5vG3vG2vG1_GiaLai: [String],
    G6vG4_GiaLai: [String],
    G4_GiaLai: [String],
    LT_GiaLai: [String],

    G8vGDB_KonTum: [String],
    G7vG5vG3vG2vG1_KonTum: [String],
    G6vG4_KonTum: [String],
    G4_KonTum: [String],
    LT_KonTum: [String],

    G8vGDB_NinhThuan: [String],
    G7vG5vG3vG2vG1_NinhThuan: [String],
    G6vG4_NinhThuan: [String],
    G4_NinhThuan: [String],
    LT_NinhThuan: [String],

    G8vGDB_PhuYen: [String],
    G7vG5vG3vG2vG1_PhuYen: [String],
    G6vG4_PhuYen: [String],
    G4_PhuYen: [String],
    LT_PhuYen: [String],

    G8vGDB_CaMau: [String],
    G7vG5vG3vG2vG1_CaMau: [String],
    G6vG4_CaMau: [String],
    G4_CaMau: [String],
    LT_CaMau: [String],

    G8vGDB_DongThap: [String],
    G7vG5vG3vG2vG1_DongThap: [String],
    G6vG4_DongThap: [String],
    G4_DongThap: [String],
    LT_DongThap: [String],

    G8vGDB_HauGiang: [String],
    G7vG5vG3vG2vG1_HauGiang: [String],
    G6vG4_HauGiang: [String],
    G4_HauGiang: [String],
    LT_HauGiang: [String],

    G8vGDB_TienGiang: [String],
    G7vG5vG3vG2vG1_TienGiang: [String],
    G6vG4_TienGiang: [String],
    G4_TienGiang: [String],
    LT_TienGiang: [String],

    G8vGDB_TraVinh: [String],
    G7vG5vG3vG2vG1_TraVinh: [String],
    G6vG4_TraVinh: [String],
    G4_TraVinh: [String],
    LT_TraVinh: [String],

    G8vGDB_HCM: [String],
    G7vG5vG3vG2vG1_HCM: [String],
    G6vG4_HCM: [String],
    G4_HCM: [String],
    LT_HCM: [String],

    G8vGDB_VinhLong: [String],
    G7vG5vG3vG2vG1_VinhLong: [String],
    G6vG4_VinhLong: [String],
    G4_VinhLong: [String],
    LT_VinhLong: [String],

    G8vGDB_VungTau: [String],
    G7vG5vG3vG2vG1_VungTau: [String],
    G6vG4_VungTau: [String],
    G4_VungTau: [String],
    LT_VungTau: [String],

    G8vGDB_KienGiang: [String],
    G7vG5vG3vG2vG1_KienGiang: [String],
    G6vG4_KienGiang: [String],
    G4_KienGiang: [String],
    LT_KienGiang: [String],

    G8vGDB_LongAn: [String],
    G7vG5vG3vG2vG1_LongAn: [String],
    G6vG4_LongAn: [String],
    G4_LongAn: [String],
    LT_LongAn: [String],

    G8vGDB_QuangBinh: [String],
    G7vG5vG3vG2vG1_QuangBinh: [String],
    G6vG4_QuangBinh: [String],
    G4_QuangBinh: [String],
    LT_QuangBinh: [String],

    G8vGDB_QuangNgai: [String],
    G7vG5vG3vG2vG1_QuangNgai: [String],
    G6vG4_QuangNgai: [String],
    G4_QuangNgai: [String],
    LT_QuangNgai: [String],

    G8vGDB_Hue: [String],
    G7vG5vG3vG2vG1_Hue: [String],
    G6vG4_Hue: [String],
    G4_Hue: [String],
    LT_Hue: [String],

    G8vGDB_TayNinh: [String],
    G7vG5vG3vG2vG1_TayNinh: [String],
    G6vG4_TayNinh: [String],
    G4_TayNinh: [String],
    LT_TayNinh: [String],

    G8vGDB_BinhThuan: [String],
    G7vG5vG3vG2vG1_BinhThuan: [String],
    G6vG4_BinhThuan: [String],
    G4_BinhThuan: [String],
    LT_BinhThuan: [String],

    G8vGDB_BinhDinh: [String],
    G7vG5vG3vG2vG1_BinhDinh: [String],
    G6vG4_BinhDinh: [String],
    G4_BinhDinh: [String],
    LT_BinhDinh: [String],

    G8vGDB_KhanhHoa: [String],
    G7vG5vG3vG2vG1_KhanhHoa: [String],
    G6vG4_KhanhHoa: [String],
    G4_KhanhHoa: [String],
    LT_KhanhHoa: [String],

    G8vGDB_DaNang: [String],
    G7vG5vG3vG2vG1_DaNang: [String],
    G6vG4_DaNang: [String],
    G4_DaNang: [String],
    LT_DaNang: [String],

    G8vGDB_DongNai: [String],
    G7vG5vG3vG2vG1_DongNai: [String],
    G6vG4_DongNai: [String],
    G4_DongNai: [String],
    LT_DongNai: [String],

    G8vGDB_SocTrang: [String],
    G7vG5vG3vG2vG1_SocTrang: [String],
    G6vG4_SocTrang: [String],
    G4_SocTrang: [String],
    LT_SocTrang: [String],

    G8vGDB_BacLieu: [String],
    G7vG5vG3vG2vG1_BacLieu: [String],
    G6vG4_BacLieu: [String],
    G4_BacLieu: [String],
    LT_BacLieu: [String],

    G8vGDB_BenTre: [String],
    G7vG5vG3vG2vG1_BenTre: [String],
    G6vG4_BenTre: [String],
    G4_BenTre: [String],
    LT_BenTre: [String],

    G8vGDB_BinhDuong: [String],
    G7vG5vG3vG2vG1_BinhDuong: [String],
    G6vG4_BinhDuong: [String],
    G4_BinhDuong: [String],
    LT_BinhDuong: [String],

    G8vGDB_BinhPhuoc: [String],
    G7vG5vG3vG2vG1_BinhPhuoc: [String],
    G6vG4_BinhPhuoc: [String],
    G4_BinhPhuoc: [String],
    LT_BinhPhuoc: [String],

    G8vGDB_CanTho: [String],
    G7vG5vG3vG2vG1_CanTho: [String],
    G6vG4_CanTho: [String],
    G4_CanTho: [String],
    LT_CanTho: [String],

    G8vGDB_QuangNam: [String],
    G7vG5vG3vG2vG1_QuangNam: [String],
    G6vG4_QuangNam: [String],
    G4_QuangNam: [String],
    LT_QuangNam: [String],

    G8vGDB_QuangTri: [String],
    G7vG5vG3vG2vG1_QuangTri: [String],
    G6vG4_QuangTri: [String],
    G4_QuangTri: [String],
    LT_QuangTri: [String],

    dt123: [String],
    dt123_day: [String],

    dt636: [String],
    dt636_day: [String],

    boso_theoThu: [String],
    phantram_theoThu: [String],
    luot_theoThu: [String],

    bang12_xh: [String],
    textleft_xh: [String],

    keno_dt: [String],
    text_keno_dt: [String],
    text_keno_dt_official: [String],
    keno_thoigian: [String],

    mega_para_open_next: [String],
    mega_number_ball: [String],
    mega_text_right: [String],
    mega_para_text_black_bold: [String],
    mega_jackpot: [String],
    mega_xsmega: [String],
    mega_ball: [String],
    mega_class_link: [String],
    mega_ball: [String],

    mega_thu4_para_open_next: [String],
    mega_thu4_number_ball: [String],
    mega_thu4_text_right: [String],
    mega_thu4_para_text_black_bold: [String],
    mega_thu4_jackpot: [String],
    mega_thu4_xsmega: [String],
    mega_thu4_ball: [String],
    mega_thu4_class_link: [String],
    mega_thu4_ball: [String],

    mega_cn_para_open_next: [String],
    mega_cn_number_ball: [String],
    mega_cn_text_right: [String],
    mega_cn_para_text_black_bold: [String],
    mega_cn_jackpot: [String],
    mega_cn_xsmega: [String],
    mega_cn_ball: [String],
    mega_cn_class_link: [String],
    mega_cn_ball: [String],

    mega_thu6_para_open_next: [String],
    mega_thu6_number_ball: [String],
    mega_thu6_text_right: [String],
    mega_thu6_para_text_black_bold: [String],
    mega_thu6_jackpot: [String],
    mega_thu6_xsmega: [String],
    mega_thu6_ball: [String],
    mega_thu6_class_link: [String],
    mega_thu6_ball: [String],

    tenTinhMTMN: [String],

    xsdt_day: [String],
    xsdt_ball: [String],
    xsdt_number: [String],

    power_class_link: [String],
    power_para_open_next: [String],
    power_number_ball: [String],
    power_text_right: [String],
    power_para_text_black_bold: [String],
    power_jackpot: [String],
    power_xspower: [String],
    power_ball: [String],

    max3d_title: [String],
    max3d_link: [String],
    G1: [String],
    G2vKK: [String],
    G3: [String],

    max3d_title_thu2: [String],
    max3d_link_thu2: [String],
    G1_thu2: [String],
    G2vKK_thu2: [String],
    G3_thu2: [String],

    MDB_XSMB_30ngay: [String],
    GDB_XSMB_30ngay: [String],
    G1_XSMB_30ngay: [String],
    G2_XSMB_30ngay: [String],
    G3vG5vG6_XSMB_30ngay: [String],
    G4_XSMB_30ngay: [String],
    G7_XSMB_30ngay: [String],
    Day_XSMB_30ngay: [String],

    MDB_XSMB_90ngay: [String],
    GDB_XSMB_90ngay: [String],
    G1_XSMB_90ngay: [String],
    G2_XSMB_90ngay: [String],
    G3vG5vG6_XSMB_90ngay: [String],
    G4_XSMB_90ngay: [String],
    G7_XSMB_90ngay: [String],
    Day_XSMB_90ngay: [String],

    max3d_title_thu4: [String],
    max3d_link_thu4: [String],
    G1_thu4: [String],
    G2vKK_thu4: [String],
    G3_thu4: [String],

    max3d_title_thu6: [String],
    max3d_link_thu6: [String],
    G1_thu6: [String],
    G2vKK_thu6: [String],
    G3_thu6: [String],

    max3d_title_pro: [String],
    max3d_link_pro: [String],
    G1_pro: [String],
    G2vKK_pro: [String],
    G3_pro: [String],

    max3d_title_pro_thu3: [String],
    max3d_link_pro_thu3: [String],
    G1_pro_thu3: [String],
    G2vKK_pro_thu3: [String],
    G3_pro_thu3: [String],

    max3d_title_pro_thu5: [String],
    max3d_link_pro_thu5: [String],
    G1_pro_thu5: [String],
    G2vKK_pro_thu5: [String],
    G3_pro_thu5: [String],

    max3d_title_pro_thu7: [String],
    max3d_link_pro_thu7: [String],
    G1_pro_thu7: [String],
    G2vKK_pro_thu7: [String],
    G3_pro_thu7: [String],

    tt_day: [String],
    tt_number: [String],

    power_thu3_class_link: [String],
    power_thu3_para_open_next: [String],
    power_thu3_number_ball: [String],
    power_thu3_text_right: [String],
    power_thu3_para_text_black_bold: [String],
    power_thu3_jackpot: [String],
    power_thu3_xspower: [String],
    power_thu3_ball: [String],

    power_thu5_class_link: [String],
    power_thu5_para_open_next: [String],
    power_thu5_number_ball: [String],
    power_thu5_text_right: [String],
    power_thu5_para_text_black_bold: [String],
    power_thu5_jackpot: [String],
    power_thu5_xspower: [String],
    power_thu5_ball: [String],

    power_thu7_class_link: [String],
    power_thu7_para_open_next: [String],
    power_thu7_number_ball: [String],
    power_thu7_text_right: [String],
    power_thu7_para_text_black_bold: [String],
    power_thu7_jackpot: [String],
    power_thu7_xspower: [String],
    power_thu7_ball: [String],

    day_haisocuoi:[String],
});

xosoResultSchema.index({ date: 1 }, { unique: true });

module.exports = mongoose.model('XosoResult', xosoResultSchema);
