const mongoose = require('mongoose');

const xosoResultSchema = new mongoose.Schema({
    date: { type: String, required: true },
    GDBMB: { type: String, required: true },
    G1MB: [String],
    G2MB: [String],
    G3MB: [String],
    G4MB: [String],
    G5MB: [String],
    G6MB: [String],
    G7MB: [String],
    createdAt: { type: Date, default: Date.now },
    MDBMB: [String],

    jackpot: [String],

    LT0MB: [String],
    LT1MB: [String],
    LT2MB: [String],
    LT3MB: [String],
    LT4MB: [String],
    LT5MB: [String],
    LT6MB: [String],
    LT7MB: [String],
    LT8MB: [String],
    LT9MB: [String],

    TKGDB: [String],

    //mn
    GDBHCM: [String],
    G1HCM: [String],
    G2HCM: [String],
    G3HCM: [String],
    G4HCM: [String],
    G5HCM: [String],
    G6HCM: [String],
    G7HCM: [String],
    G8HCM: [String],

    GDBDT: [String],
    G1DT: [String],
    G2DT: [String],
    G3DT: [String],
    G4DT: [String],
    G5DT: [String],
    G6DT: [String],
    G7DT: [String],
    G8DT: [String],

    GDBCM: [String],
    G1CM: [String],
    G2CM: [String],
    G3CM: [String],
    G4CM: [String],
    G5CM: [String],
    G6CM: [String],
    G7CM: [String],
    G8CM: [String],
    GDBDN: [String],
    G1DN: [String],
    G2DN: [String],
    G3DN: [String],
    G4DN: [String],
    G5DN: [String],
    G6DN: [String],
    G7DN: [String],
    G8DN: [String],
    GDBCT: [String],
    G1CT: [String],
    G2CT: [String],
    G3CT: [String],
    G4CT: [String],
    G5CT: [String],
    G6CT: [String],
    G7CT: [String],
    G8CT: [String],
    GDBST: [String],
    G1ST: [String],
    G2ST: [String],
    G3ST: [String],
    G4ST: [String],
    G5ST: [String],
    G6ST: [String],
    G7ST: [String],
    G8ST: [String],
    GDBTN: [String],
    G2TN: [String],
    G3TN: [String],
    G4TN: [String],
    G5TN: [String],
    G6TN: [String],
    G7TN: [String],
    G8TN: [String],

    GDBAG: [String],
    G1AG: [String],
    G2AG: [String],
    G3AG: [String],
    G4AG: [String],
    G5AG: [String],
    G6AG: [String],
    G7AG: [String],
    G8AG: [String],

    GDBBTH: [String],
    G1BTH: [String],
    G2BTH: [String],
    G3BTH: [String],
    G4BTH: [String],
    G5BTH: [String],
    G6BTH: [String],
    G7BTH: [String],
    G8BTH: [String],

    GDBVL: [String],
    G1VL: [String],
    G2VL: [String],
    G3VL: [String],
    G4VL: [String],
    G5VL: [String],
    G6VL: [String],
    G7VL: [String],
    G8VL: [String],

    GDBBD: [String],
    G1BD: [String],
    G2BD: [String],
    G3BD: [String],
    G4BD: [String],
    G5BD: [String],
    G6BD: [String],
    G7BD: [String],
    G8BD: [String],

    GDBTV: [String],
    G1TV: [String],
    G2TV: [String],
    G3TV: [String],
    G4TV: [String],
    G5TV: [String],
    G6TV: [String],
    G7TV: [String],
    G8TV: [String],

    LT0DN: [String],
    LT1DN: [String],
    LT2DN: [String],
    LT3DN: [String],
    LT4DN: [String],
    LT5DN: [String],
    LT6DN: [String],
    LT7DN: [String],
    LT8DN: [String],
    LT9DN: [String],
    LT0CT: [String],
    LT1CT: [String],
    LT2CT: [String],
    LT3CT: [String],
    LT4CT: [String],
    LT5CT: [String],
    LT6CT: [String],
    LT7CT: [String],
    LT8CT: [String],
    LT9CT: [String],
    LT0ST: [String],
    LT1ST: [String],
    LT2ST: [String],
    LT3ST: [String],
    LT4ST: [String],
    LT5ST: [String],
    LT6ST: [String],
    LT7ST: [String],
    LT8ST: [String],
    LT9ST: [String],

    LT0TN: [String],
    LT1TN: [String],
    LT2TN: [String],
    LT3TN: [String],
    LT4TN: [String],
    LT5TN: [String],
    LT6TN: [String],
    LT7TN: [String],
    LT8TN: [String],
    LT9TN: [String],

    LT0AG: [String],
    LT1AG: [String],
    LT2AG: [String],
    LT3AG: [String],
    LT4AG: [String],
    LT5AG: [String],
    LT6AG: [String],
    LT7AG: [String],
    LT8AG: [String],
    LT9AG: [String],

    LT0BTH: [String],
    LT1BTH: [String],
    LT2BTH: [String],
    LT3BTH: [String],
    LT4BTH: [String],
    LT5BTH: [String],
    LT6BTH: [String],
    LT7BTH: [String],
    LT8BTH: [String],
    LT9BTH: [String],

    LT0HCM: [String],
    LT1HCM: [String],
    LT2HCM: [String],
    LT3HCM: [String],
    LT4HCM: [String],
    LT5HCM: [String],
    LT6HCM: [String],
    LT7HCM: [String],
    LT8HCM: [String],
    LT9HCM: [String],

    LT0DT: [String],
    LT1DT: [String],
    LT2DT: [String],
    LT3DT: [String],
    LT4DT: [String],
    LT5DT: [String],
    LT6DT: [String],
    LT7DT: [String],
    LT8DT: [String],
    LT9DT: [String],

    LT0CM: [String],
    LT1CM: [String],
    LT2CM: [String],
    LT3CM: [String],
    LT4CM: [String],
    LT5CM: [String],
    LT6CM: [String],
    LT7CM: [String],
    LT8CM: [String],
    LT9CM: [String],

    //mt
    GDBPY: [String],
    G1PY: [String],
    G2PY: [String],
    G3PY: [String],
    G4PY: [String],
    G5PY: [String],
    G6PY: [String],
    G7PY: [String],
    G8PY: [String],

    GDBTTH: [String],
    G1TTH: [String],
    G2TTH: [String],
    G3TTH: [String],
    G4TTH: [String],
    G5TTH: [String],
    G6TTH: [String],
    G7TTH: [String],
    G8TTH: [String],

    GDBKT: [String],
    G1KT: [String],
    G2KT: [String],
    G3KT: [String],
    G4KT: [String],
    G5KT: [String],
    G6KT: [String],
    G7KT: [String],
    G8KT: [String],

    GDBKH: [String],
    G1KH: [String],
    G2KH: [String],
    G3KH: [String],
    G4KH: [String],
    G5KH: [String],
    G6KH: [String],
    G7KH: [String],
    G8KH: [String],

    GDBGL: [String],
    G1GL: [String],
    G2GL: [String],
    G3GL: [String],
    G4GL: [String],
    G5GL: [String],
    G6GL: [String],
    G7GL: [String],
    G8GL: [String],

    GDBNT: [String],
    G1NT: [String],
    G2NT: [String],
    G3NT: [String],
    G4NT: [String],
    G5NT: [String],
    G6NT: [String],
    G7NT: [String],
    G8NT: [String],

    GDBDNA: [String],
    G1DNA: [String],
    G2DNA: [String],
    G3DNA: [String],
    G4DNA: [String],
    G5DNA: [String],
    G6DNA: [String],
    G7DNA: [String],
    G8DNA: [String],

    GDBKH: [String],
    G1KH: [String],
    G2KH: [String],
    G3KH: [String],
    G4KH: [String],
    G5KH: [String],
    G6KH: [String],
    G7KH: [String],
    G8KH: [String],

    GDBQB: [String],
    G1QB: [String],
    G2QB: [String],
    G3QB: [String],
    G4QB: [String],
    G5QB: [String],
    G6QB: [String],
    G7QB: [String],
    G8QB: [String],

    GDBBDI: [String],
    G1BDI: [String],
    G2BDI: [String],
    G3BDI: [String],
    G4BDI: [String],
    G5BDI: [String],
    G6BDI: [String],
    G7BDI: [String],
    G8BDI: [String],

    GDBQT: [String],
    G1QT: [String],
    G2QT: [String],
    G3QT: [String],
    G4QT: [String],
    G5QT: [String],
    G6QT: [String],
    G7QT: [String],
    G8QT: [String],

    LT0DNA: [String],
    LT1DNA: [String],
    LT2DNA: [String],
    LT3DNA: [String],
    LT4DNA: [String],
    LT5DNA: [String],
    LT6DNA: [String],
    LT7DNA: [String],
    LT8DNA: [String],
    LT9DNA: [String],
    
    LT0KT: [String],
    LT1KT: [String],
    LT2KT: [String],
    LT3KT: [String],
    LT4KT: [String],
    LT5KT: [String],
    LT6KT: [String],
    LT7KT: [String],
    LT8KT: [String],
    LT9KT: [String],

    LT0TTH: [String],
    LT1TTH: [String],
    LT2TTH: [String],
    LT3TTH: [String],
    LT4TTH: [String],
    LT5TTH: [String],
    LT6TTH: [String],
    LT7TTH: [String],
    LT8TTH: [String],
    LT9TTH: [String],

    LT0KH: [String],
    LT1KH: [String],
    LT2KH: [String],
    LT3KH: [String],
    LT4KH: [String],
    LT5KH: [String],
    LT6KH: [String],
    LT7KH: [String],
    LT8KH: [String],
    LT9KH: [String],

    LT0QB: [String],
    LT1QB: [String],
    LT2QB: [String],
    LT3QB: [String],
    LT4QB: [String],
    LT5QB: [String],
    LT6QB: [String],
    LT7QB: [String],
    LT8QB: [String],
    LT9QB: [String],

    LT0BDI: [String],
    LT1BDI: [String],
    LT2BDI: [String],
    LT3BDI: [String],
    LT4BDI: [String],
    LT5BDI: [String],
    LT6BDI: [String],
    LT7BDI: [String],
    LT8BDI: [String],
    LT9BDI: [String],

    LT0QT: [String],
    LT1QT: [String],
    LT2QT: [String],
    LT3QT: [String],
    LT4QT: [String],
    LT5QT: [String],
    LT6QT: [String],
    LT7QT: [String],
    LT8QT: [String],
    LT9QT: [String],
    //keno
    keno: [String],
    pad_012: [String],
    td_text16: [String],

    //jackpot
    para_open_next: [String],
    number_ball: [String],
    text_right: [String],
    para_text_black_bold: [String],
    xsmega: [String],

    //max3d

    max3dg1: [String],
    max3dg24: [String],
    max3dg3: [String],
    titlemax3d: [String],

    //lotogan
    daylotogan: [String],
    lotogan: [String],
    loto: [String],
    daylotogan2: [String],

    //lotogancv
    boso2: [String],
    boso2_ngayve: [String],

    //tklogandau
    tklogandau : [String],
    tklogandauso:[String],
 
    tkloganduoiso:[String],
    
    TKGDBTH:[String],
    phantram_TKLXH: [String],
    luot_TKLXH: [String],
    boso_TKLXH:[String],

    slxh_TKKCB : [String],
    boso_TKKCB : [String],
   top10_TKKCB : [String],

    kyquay_TKKBS : [String],
    lon_TKKBS :    [String],
    be_TKKBS :     [String],
    chan_TKKBS :   [String],
    le_TKKBS :     [String],
    combo_TKKBS : [String],

    phantram_TKkdencc: [String],
    luot_TKkdencc: [String],
    boso_TKkdencc:[String],
    haisocuoi : [String],

    G8vGDB_AnGiang : [String],
    G7vG5vG2vG1_AnGiang : [String],
    G6_AnGiang : [String],
    G4vG3_AnGiang : [String],

    dt123 : [String],
});

xosoResultSchema.index({ date: 1 }, { unique: true });

module.exports = mongoose.model('XosoResult', xosoResultSchema);
